config:
  backup: true
  create: true
  dotpath: .
dotfiles:
  d_yay:
    src: config/yay
    dst: ~/.config/yay
    link: link
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    link: link
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    link: link_children
    upignore:
    - '*/fish_variables'
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
    link: link
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    link: link
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
    link: link
  d_xresources:
    src: config/Xresources
    dst: ~/.config/Xresources
    link: link
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    link: link
  d_compton:
    src: config/compton
    dst: ~/.config/compton
    link: link
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
    link: link
  d_emacs:
    src: emacs/emacs.d
    dst: ~/.emacs.d
    link: link
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
    link: link
profiles:
  manta:
    dotfiles:
    - d_yay
    - d_i3
    - d_fish
    - d_kitty
    - f_xresources
    - f_xinitrc
    - d_xresources
    - f_gitconfig
    - d_compton
    - d_alacritty
    - d_emacs
    - d_polybar
