config:
  backup: true
  create: true
  dotpath: .
dotfiles:
  d_yay:
    src: config/yay
    dst: ~/.config/yay
    link: link
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    link: link
  d_fish:
    src: config/fish
    dst: ~/.config/fish
    link: link_children
    upignore:
    - '*/fish_variables'
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
    link: link
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
    link: link
  d_xresources:
    src: config/Xresources
    dst: ~/.config/Xresources
    link: link
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    link: link
  d_picom:
    src: config/picom
    dst: ~/.config/picom
    link: link
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
    link: link
  d_emacs:
    src: emacs/emacs.d
    dst: ~/.emacs.d
    link: link
  f_xbindkeysrc:
    src: xbindkeysrc
    dst: ~/.xbindkeysrc
    link: link
profiles:
  manta:
    dotfiles:
    - d_yay
    - d_i3
    - d_fish
    - f_xresources
    - f_xinitrc
    - d_xresources
    - f_gitconfig
    - d_picom
    - d_alacritty
    - d_emacs
    - f_xbindkeysrc
  chlorophyll:
    dotfiles:
    - d_yay
    - d_i3
    - d_fish
    - f_xresources
    - f_xinitrc
    - d_xresources
    - f_gitconfig
    - d_picom
    - d_alacritty
    - d_emacs
    - f_xbindkeysrc
