addSbtPlugin("com.eed3si9n" % "sbt-dirty-money" % "0.1.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.8.5")
addSbtPlugin("com.eed3si9n" % "sbt-man" % "0.1.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.2.0")
addSbtPlugin("com.eed3si9n" % "sbt-sh" % "0.1.0")
addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.5")
