set nocompatible

" Show line numbers
set number

" Allow hidden buffers, don't limit to 1 file per window/split
set hidden

inoremap jk <esc>
inoremap kj <esc>

call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ntpeters/vim-better-whitespace'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/seoul256.vim'
Plug 'jceb/vim-orgmode'
Plug 'tpope/vim-speeddating'
Plug 'akutschi/vim-colokschi'
Plug '/usr/local/opt/fzf' | Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'mtth/scratch.vim'
Plug 'derekwyatt/vim-scala'
call plug#end()

" vim-airline config
:let g:airline_theme='papercolor'

if has('mac') || has ('macunix')
    let g:airline_powerline_fonts = 1
    set guifont=Monaco\ for\ Powerline:h12
endif

let mapleader=';'

map <C-n> :NERDTreeToggle<CR>

colo seoul256
" colo colokschi-light
set background=dark

set tabstop=4
set softtabstop=4
set expandtab

filetype plugin indent on
