hs.hotkey.bind({'cmd', 'alt', 'ctrl'}, 'r', function()
    hs.reload()
    hs.alert.show('Config Reloaded')
end)

jumpMode = hs.hotkey.modal.new('cmd', 'j')
jumpMode:bind({}, 's', function()
    hs.application.launchOrFocus('Spotify.app')
    jumpMode:exit()
end)

jumpMode:bind({}, 't', function()
    hs.application.launchOrFocus('iTerm.app')
    jumpMode:exit()
end)

jumpMode:bind({}, 'h', function()
    hs.application.launchOrFocus('HipChat.app')
    jumpMode:exit()
end)

jumpMode:bind({}, 'm', function()
    hs.application.launchOrFocus('Airmail 3.app')
    jumpMode:exit()
end)

jumpMode:bind({}, 'o', function()
    hs.application.launchOrFocus('Microsoft Outlook.app')
    jumpMode:exit()
end)
